In [5]:
import numpy as np
from numpy import linalg
import open3d as o3d
import trimesh

def display_inlier_outlier(cloud, ind):
    inlier_cloud = cloud.select_by_index(ind)
    outlier_cloud = cloud.select_by_index(ind, invert=True)

    print("Showing outliers (red) and inliers (gray): ")
    outlier_cloud.paint_uniform_color([1, 0, 0])
    inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
    o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])

pcd = o3d.io.read_point_cloud("test1(2).pcd")

voxel_down_pcd = pcd.voxel_down_sample(voxel_size=0.002)
o3d.visualization.draw_geometries([voxel_down_pcd])

# cl, ind = voxel_down_pcd.remove_statistical_outlier(nb_neighbors=20,
#                                                         std_ratio=2.0)
# display_inlier_outlier(voxel_down_pcd, ind)


# uni_down_pcd = pcd.uniform_down_sample(every_k_points=5)
# o3d.visualization.draw_geometries([uni_down_pcd])




# out_arr = np.asarray(pcd.points)
# for x in out_arr:
#     print(x)  
# cloud = o3d.io.read_point_cloud("test.pcd") # Read the point cloud
# o3d.visualization.draw_geometries([pcd])



Jupyter environment detected. Enabling Open3D WebVisualizer.


AttributeError: partially initialized module 'open3d' has no attribute 'visualization' (most likely due to a circular import)

In [21]:
import numpy as np
import open3d as o3d

#pcd = o3d.io.read_point_cloud('./meshdata2.xyz')
# pcd = o3d.io.read_point_cloud("test1(2).pcd")
# P = o3d.io.read_point_cloud("test1(2).pcd")
# print(P)

P = np.load("pnt_cld.npy")
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(P)
# pcd.estimate_normals()
pcd = pcd.uniform_down_sample(10)
pcd.estimate_normals()


mesh, _ = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=4)

mesh.paint_uniform_color(np.array([0.7, 0.7, 0.7]))
o3d.io.write_triangle_mesh(("mesh.ply"), mesh)
mesh = o3d.io.read_triangle_mesh('mesh.ply')
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])

# o3d.visualization.draw_geometries([pcd])



# voxel_down_pcd.estimate_normals()

# # to obtain a consistent normal orientation
# voxel_down_pcd.orient_normals_towards_camera_location(voxel_down_pcd.get_center())

# # or you might want to flip the normals to make them point outward, not mandatory
# voxel_down_pcd.normals = o3d.utility.Vector3dVector( - np.asarray(voxel_down_pcd.normals))

# # surface reconstruction using Poisson reconstruction
# mesh, _ = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(voxel_down_pcd, depth=10)

# # paint uniform color to better visualize, not mandatory
# mesh.paint_uniform_color(np.array([0.7, 0.7, 0.7]))

# o3d.io.write_triangle_mesh('a.ply', mesh)
# o3d.visualization.draw_geometries([mesh])

[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues

In [1]:
mesh = o3d.io.read_triangle_mesh('a.ply')
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])


NameError: name 'o3d' is not defined

In [25]:
import numpy as np
import utils
import matplotlib.pyplot as plt
import random
import point_cloud_utils as pcu
from mpl_toolkits.mplot3d import Axes3D 
import scipy
%matplotlib widget

P = np.load("pnt_cld.npy")
print(P)
# pcd.points = o3d.utility.Vector3dVector(P)
# pcd.estimate_normals()
# N = np.array(pcd.normals)
# # print(N)
# # P = o3d.io.read_point_cloud("test1(2).pcd")
# # P = np.asarray(P.points)
# # print(len(P))
# # N = pcu.estimate_point_cloud_normals_knn(P, 3000)
# # N = N[1]
# # print(N)
# # print(len(N))
# NUM_ITER = 10000
# E = 0.1
# center_main = 0
# radii_main = 0
# axis_main = 0
# inliers_main = 0
# for i in range(0, NUM_ITER):
#     # Sampling Radius
#     radii = random.uniform(0.01,0.05)
#     # np.random.shuffle(radii)
#     # radii = radii[0]
#     # Sample two points
#     sample_ = random.sample(range(0,max(np.shape(P))),2)
#     sample_point = [P[a] for a in sample_]
#     sample_normal = [N[a] for a in sample_]
#     idx = np.random.randint(0,2)
#     # Finding Center
#     center = sample_point[idx]+(radii*sample_normal[idx])
#     # Finding Axis
#     sample_axis = np.cross(sample_normal[0], sample_normal[1]).reshape(-1,1)
#     # Projecing points and centers
#     project_points = P@(np.identity(3)-sample_axis@sample_axis.T)
#     project_center = center.reshape(1,-1)@(np.identity(3)-sample_axis@sample_axis.T)
#     # Finding Inliers
#     dists = abs(scipy.spatial.distance.cdist(project_points, project_center, metric='euclidean'))
#     dists = abs(dists-radii)
#     # print(dists)
#     num_inliers = np.sum(dists < E)
#     if num_inliers > inliers_main:
#         center_main = project_center.reshape(-1,1)
#         radii_main = radii
#         axis_main = sample_axis
#         inliers_main = num_inliers

# axis = axis_main / np.linalg.norm(axis_main)
# ax = plt.figure().add_subplot(projection='3d')
# ax.view_init(30, -115)
# utils.plot_cylinder(ax, center, axis, radii_main)
# ax.scatter(*P[::4].T, s=0.04)
# plt.tight_layout()
# plt.show()


[[ 0.05712999  0.12369378 -0.82499999]
 [ 0.05867523  0.12369378 -0.82499999]
 [ 0.06007449  0.12339392 -0.82300001]
 ...
 [ 0.08643119 -0.12944569 -0.796     ]
 [ 0.08792212 -0.12944569 -0.796     ]
 [ 0.0896377  -0.12977093 -0.79799998]]


In [86]:
import numpy as np
import open3d as o3d

P = np.load("pnt_cld.npy")
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(P)
pcd.estimate_normals()
pcd = pcd.uniform_down_sample(10)
pcd.estimate_normals()

# mesh, _ = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=10)
# voxel_down_pcd = pcd.voxel_down_sample(voxel_size=0.005)

# voxel_down_pcd.estimate_normals()

# voxel_down_pcd.orient_normals_towards_camera_location(voxel_down_pcd.get_center())

# voxel_down_pcd.normals = o3d.utility.Vector3dVector( - np.asarray(voxel_down_pcd.normals))


# mesh, _ = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(voxel_down_pcd, depth=9)

# o3d.visualization.draw_geometries([mesh])



# hull, _ = pcd.compute_convex_hull()
# hull_ls = o3d.geometry.LineSet.create_from_triangle_mesh(hull)
# hull_ls.paint_uniform_color((1, 0, 0))
# mesh = o3d.geometry.TriangleMesh
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth = 9)

# mesh.paint_uniform_color(np.array([0.7, 0.7, 0.7]))

# Visualize the mesh
o3d.visualization.draw_geometries([mesh])

# o3d.io.write_triangle_mesh(("mesh.ply"), mesh)

# mesh = o3d.io.read_triangle_mesh('mesh.ply')
# mesh.compute_vertex_normals()
# o3d.visualization.draw_geometries([mesh])

AttributeError: 'tuple' object has no attribute 'paint_uniform_color'

In [ ]:
# o3d.visualization.draw_geometries([pcd])

# voxel_down_pcd = pcd.voxel_down_sample(voxel_size=0.005)

# voxel_down_pcd.estimate_normals()

# voxel_down_pcd.orient_normals_towards_camera_location(voxel_down_pcd.get_center())

# voxel_down_pcd.normals = o3d.utility.Vector3dVector( - np.asarray(voxel_down_pcd.normals))

In [20]:
import numpy as np
import open3d as o3d



P = np.load("pnt_cld.npy")
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(P)
# pcd.estimate_normals()
pcd.estimate_normals()
pcd = pcd.uniform_down_sample(10)
mesh, _ = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=4)
mesh.paint_uniform_color(np.array([0.7, 0.7, 0.7]))
o3d.io.write_triangle_mesh("mesh.ply", mesh)
# self.path = "mesh.ply"
mesh = o3d.io.read_triangle_mesh('mesh.ply')
mesh.compute_vertex_normals()

# o3d.visualization.draw_geometries([mesh])

[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues
          getValue assumes leaf node
[WARNING] /home/runner/work/Open3D/Open3D/3rdparty/PoissonRecon/PoissonRecon/Src/FEMTree.Evaluation.inl (Line 155)
          _getValues

TriangleMesh with 1732 points and 3382 triangles.